### ISSUE TITLE
Fill in kernel-loaded text-data segment gap in libdynamorio with PROT_NONE mmap

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1659]
Xref https://github.com/DynamoRIO/drmemory/issues/1706

ld.so fills in the gaps between text and data segments (due to large-page-size-aligned data segments) with PROT_NONE mmaps and our private loader should probably do the same.

**Comment by derekbruening** [comment]
My bad, we are already doing this by making the initial full-size reservation PROT_NONE.  All we need to do is fill the gap from the kernel loading us for a no-conflict-with-app early injection.

**Comment by zhaoqin** [comment]
Yes, xref elf_loader_map_phdrs, we put PROT_NONE on those gaps:
            if (seg_base != last_end) {
                /* XXX: a hole, I reserve this space instead of unmap it */
                size_t hole_size = seg_base - last_end;
                (*prot_func)(last_end, hole_size, MEMPROT_NONE);
            }

In elf_loader_map_phdrs, we first mmap the whole image file into memory, and then load segments one by one, and fill the gap using mprotect with MEMPROT_NONE, (need this mprotect since the image size might not be large enough and not reach this gap).
