### ISSUE TITLE
drrun -t drcov fail to get option passed via command line

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1750]
run with -t
>$ ls /tmp/drcov/
>$ ./bin64/drrun -debug -t drcov -logdir /tmp/drcov -- ls
...
>$ ls /tmp/drcov/

so the log file is not put into /tmp/drcov.

run with -c
>$ ./bin64/drrun -debug -c ./tools/lib64/debug/libdrcov.so -logdir /tmp/drcov -- ls
>...
>$ ls /tmp/drcov/
>drcov.ls.04688.0000.proc.log

Investigate more:
-c has option:  -client_lib '.../tools/lib64/debug/libdrcov.so;0;"-logdir" "/tmp/drcov"'
-t has option: -client_lib '.../tools/lib64/debug/libdrcov.so;0;"" "-logdir" "/tmp/drcov"'
and DR saw the "" think it is end of the option.
The "" is introduced by tools/drcov.drrun64 having an empty TOOL_OPS= entry.

**Comment by derekbruening** [comment]
This could have perhaps re-opened #1736 instead which is what triggered it.  While the empty entry doesn't seem ideal, that should just result in an empty string in argv[1] at worst, which might mess up the tool depending on its parsing.  But the other problem is that the tokenizer should return an empty string for a quoted empty string, rather than claiming there are no more tokens.
