### ISSUE TITLE
legacy flat option string from dr_get_options() can have stripped essential quotes when not using drrun

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1755]
in dr_get_options, it copies the option string from argv to a string.
```
            for (j = 1/*skip client lib*/; j < client_libs[i].argc; j++) {
                if (!print_to_buffer(client_libs[i].legacy_options,
                                     BUFFER_SIZE_ELEMENTS(client_libs[i].legacy_options),
                                     &sofar, "%s%s", (j == 1) ? "" : " ",
                                     client_libs[i].argv[j]))
                    break;
            }
```
In Dr.Memory, at least on my machine, the logdir is set to /tmp/Dr. Memory
```
(gdb) p client_libs[i].argv[3]
$6 = 0x502d1638 "/tmp/Dr. Memory"
```
so the /tmp/Dr. Memory will be directly copied into the legacy string and pass to Dr.Memory,
then Dr.Memory's own option parser will see -logdir /tmp/Dr. Memory.
Origainlly, it will see `-logdir` `/tmp/Dr. Memory`, which has no problem.

So we should either blindly add `` around each argv or we add `` if we saw a white-space there.

**Comment by derekbruening** [comment]
The #1736 solution revolves around drrun re-quoting args (to do so inside drconfiglib would require making whole new interfaces).  However, other frontends like Dr. Memory or Dr. Strace have not been changed to re-quote, leading to essential quotes for tokens with spaces or other sensitive
characters being stripped out.

**Comment by derekbruening** [comment]
We can't do something like adding quotes in dr_get_options() because we'll
break somebody no matter what we do.  A client not expecting quotes cannot
handle quotes.  A client doing its own tokenizing wants quotes around a
path with spaces, but a client that takes one arg and passes the whole
thing (the dr_get_options() result) to dr_open_file() will be broken by
having quotes there while it will work fine w/o any quotes.

I propose a targeted soln.  If we assume that a frontend is either
re-quoting everything or nothing, we try to detect which, and instead of
re-flattening we keep a copy for the nothing cases.  Then the only problem
is some 3rd party frontend that does partial quoting or sthg weird that
fools us which I can live with.  Seems the best soln as it will keep back
compat for nearly all cases.
