### ISSUE TITLE
execution exception not passed to client handler on Windows

### ISSUE THREAD

**Issue by kvnesterov** [DynamoRIO/dynamorio#1775]
DynamoRIO won't call exception handler registered with dr_register_exception_event
typedef void (*f_t)();
int main(int argc, char *argv[])
{
  f_t a = (f_t)1;
  a();
  return 0;
}

Expected: it will works the same as on sample. 
  *(char *)(0x20) = 0x1;

It will be the same exception on this two samples on windows machine - STATUS_ACCESS_VIOLATION.

**Comment by derekbruening** [comment]
Xref #329
Xref https://github.com/DynamoRIO/drmemory/issues/1412

**Comment by derekbruening** [comment]
On Windows this forged exception goes through the raise exception path which has little processing (b/c no xl8 needed) and fails to notify the client.

Looks like on Linux we do pass this to the client signal event today.
It has raw_mcontext_valid == false (which implies a non-inside-code-cache
fault).  raw_mcontext would equal mcontext anyway.

On Windows we don't have such a field: so I guess we'll be asymmetric and
have raw_mcontext filled in there?

On Linux, dr_siginfo_t->access_address is NULL -- but so is
siginfo_t.si_addr natively so that seems ok.

**Comment by douggard** [comment]
I have two conditions that don't get exceptions in DynamoRio on Windows.

```asm
stack_ptr_ret_t PROC
  prologue
  lea     rcx, null_data
  mov     rdx, null_len
  mcall   prep_test        
  mcall   read_file_8
  mov     rsp, rbp
  pop     rbp
  mov     rsp, rax         ; replace stack with rax
  ret                      ; return using bad stack 
stack_ptr_ret_t ENDP
```

```asm
double_free_nt PROC
  prologue
  sub     rsp, 8          ; rbp+8
  mcall   GetProcessHeap
  mov     [rbp+8], rax    ; save heap
  mov     rcx, rax
  mov     rdx, 0
  mov     r8, 8
  mcall   HeapAlloc
  mov     rcx, [rbp+8]    ; heap
  xor     rdx, rdx       
  mov     [rax], rdx      ; set value stored to 0
  push    rax             ; store address
  mov     r8, rax         ; mem
  mcall   HeapFree
  mov     rcx, [rbp+8]    ; heap
  xor     rdx, rdx       
  pop     r8              ; mem
  mcall   HeapFree
  add     rsp, 8
  epilogue
double_free_nt ENDP
```

Both of these just lead to the `Hang on while Windows reports this problem to Microsoft...`, then the `program.exe has stopped working [Close Program]` dialog.

I figure these exceptions are not being passed to the client. Do you have any insight into when Windows does not pass exceptions like this?

In windbg the first gives an access violation while the second ends up in `RtlReportCriticalFailure`. Maybe for the second we can hook the reporting function, but why don't we get the first?

**Comment by derekbruening** [comment]
DR sees exceptions which come from the kernel into user mode at ntdll!KiUserExceptionDispatcher.

It looks like your first one is an unwritable stack.  Such a situation is not recoverable from user mode on Windows.  There is not alternate fault handling stack like there is on UNIX, so when the Windows kernel tries to set up exception info on the app stack to invoke ntdll!KiUserExceptionDispatcher it fails due to the stack being unwritable and has no recourse but to kill the process.  There is nothing DR can do from its position inside that process.

The second one is not a real fault and is just running user-mode code that never goes into the kernel and so never hits ntdll!KiUserExceptionDispatcher.
