### ISSUE TITLE
Equivalent PIN APIs

### ISSUE THREAD

**Issue by illera88** [DynamoRIO/dynamorio#1876]
Hi,

I've been looking for the equivalent DynamoRio functions for these three PIN ones but I can't find them. Are there similar functions in DynamoRio?
[INS_IsMemoryRead](http://www.cs.virginia.edu/kim/publicity/pin/docs/29972/Pin/html/group__INS__BASIC__API__GEN__IA32.html#g52d77b7e3ad272c7aed02875dc9907d5) 
[INS_IsMemoryWrite](http://www.cs.virginia.edu/kim/publicity/pin/docs/29972/Pin/html/group__INS__BASIC__API__GEN__IA32.html#g9b5d5f5c2a4b892fd713810b11639bac)
[INS_HasMemoryRead2](http://www.cs.virginia.edu/kim/publicity/pin/docs/29972/Pin/html/group__INS__BASIC__API__GEN__IA32.html#g9c8a496fac7601e844cb88998c2bc107)

Thank you for your help.

**Comment by derekbruening** [comment]
Normally a question should be sent to the mailing list https://groups.google.com/forum/#!forum/dynamorio-users rather than opening a bug in the issue tracker.

instr_reads_memory() http://dynamorio.org/docs/dr__ir__instr_8h.html#ae408fe229bea0aa800cddb6b911c0e94

instr_writes_memory()
http://dynamorio.org/docs/dr__ir__instr_8h.html#ae1aac8cef8bb6ab075238e38ad6888a9

To see how many memory operands there are, iterate the source operands and use opnd_is_memory_reference http://dynamorio.org/docs/dr__ir__opnd_8h.html#a5ed7af0d7ea648245c8efd77b30d7e69
