### ISSUE TITLE
Tests not building when F_SETPIPE_SZ not defined

### ISSUE THREAD

**Issue by algr** [DynamoRIO/dynamorio#1887]
drcachesim/common/named_pipe_unix.cpp uses F_SETPIPE_SZ.  As well as not being available on MacOS (already handled in the source) this also isn't available on older Linux kernels or distributions, notably RHEL6.

Since linux/fcntl.h defines these constants as macros, we can just test if it's defined and fall back to returning true if not.

**Comment by derekbruening** [comment]
To support building on a new distro not already running the test suite regularly, please consider contributing cycles on a such a machine to run a cron job test suite and push the results to our CDash server.  Otherwise, building there may break again at some point in the future with no one noticing.

However, this sounds like more than just a build issue for a DR dev: it sounds like a drcachesim problem when running on such machines.
