### ISSUE TITLE
[A64] implement signals_pending check in append_fcache_enter_prologue() for AArch64

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2043]
The signals_pending check in append_fcache_enter_prologue() for #2019 for AArch64 was not implemented due to the lack of conditional branch generation support.  This issue covers implementing it once the instruction creation routines are in place and enabling the signal_race\* tests.

**Comment by abhinav92003** [comment]
This should be unblocked now, as we have `XINST_CREATE_jump_cond` for AArch64.

https://github.com/DynamoRIO/dynamorio/blob/6c638197ce9e651812f33b4f31f7710d94f0cc6d/core/ir/aarch64/instr_create.h#L327

**Comment by abhinav92003** [comment]
Closed this issue in PR #4453.

(Github didn't close this issue automatically because it needs the 'fixes' string separately for each issue apparently: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

The `linux.signal_racesys` test has been enabled for AArch64. However, `linux.signal_race` seems to have some other issue too -- currently, it just hangs. Updated the TODO for that.
