### ISSUE TITLE
DrCov / tracedump binary_trace version mismatch

### ISSUE THREAD

**Issue by richinseattle** [DynamoRIO/dynamorio#2139]
$ bin64/drrun.exe -t drcov --  /c/tools/accesschk64.exe c:
$ samples/bin64/tracedump.exe drcov.accesschk64.exe.13600.0000.proc.log
Error: file version 1329812036 does not match tool version 602

The file version when converted to hex and interpreted as ascii is 'OCRD'

I tested this on both 6.2.0 and latest git today, Windows 10 x64

**Comment by zhaoqin** [comment]
tracedump is not used with drcov.
Xref
https://github.com/DynamoRIO/dynamorio/blob/master/api/samples/tracedump.c#L33
for tracedump
And
drcov2lcov http://dynamorio.org/docs/page_drcov.html for drcov post
processing.

**Comment by richinseattle** [comment]
Searching through git for "tracedump_binary", I see its in core/options.h but I'm having difficulty understanding what tools output this format? My intent is to have a fast coverage or edge trace tool that outputs the tracedump_binary format so I can read it with the standalone tracedump tool.

**Comment by derekbruening** [comment]
Normally "trace" implies sequential ordering, which is not what coverage information contains.

Dumping DR's traces (which capture hot code) via -tracedump_* is a feature provided by DR itself rather than being in any separate client tool.

The instrace sample produces a trace of all executed instructions, but if only coverage is needed, drcov is much, much faster.
