### ISSUE TITLE
Hi,Which regs can be stolen for using in dynamoRIO on ARM？

### ISSUE THREAD

**Issue by jiqizaisikao** [DynamoRIO/dynamorio#2291]
Sir:
    I have read the source code of dynamoRIO  on ARM,it seems that  dynamoRIO uses p15 c13 reg("mrc  p15, 0, r0, c13, c0, 2")as stolen for keeping some data。Now, I want another regs to be  stolen for holding some other data,I have tried so many regs of ARM, but id seeems that the system will use them at some time.So ,is there anyone can tell me which regs can be stolen on ARM.The stolen reg  used by dynamoRIO is really perfect!

**Comment by egrimley** [comment]
This is a question rather than a bug/issue. You should post it to dynamorio-users.

That "p15 c13" thing is a system register used by the app for thread-local storage. DynamoRIO steals an ordinary register (R10 by default) for its own use. There are no registers you can use without asking, but drreg.h has an API for reserving a register when you need one for your instrumentation.
