### ISSUE TITLE
recover all the comments on the DR bug reports that were pre-github

### ISSUE THREAD

**Issue by jgbbdxdqts** [DynamoRIO/dynamorio#2318]
All the comments on the DR bug reports that were pre-github were deleted.

Except of course by the beautiful derekbruening

If you're reading the bug reports and feel like it's some mentally unstable person talking to themself, think again

**Comment by zhaoqin** [comment]
DynamoRIO was in google code (which is shut down now) before moving to github. Derek took great effort to pull all the issues and comments from google code issue tracker to github. Because of the github limitation, all the comments are shown as left by derekbruening, but it also has the information "from whom" in the content.

**Comment by jgbbdxdqts** [comment]
A long history of bug reports with detailed commentary can be absolutely vital not only for newcomers to DR, but also for those who are not (but also not founders of DR) which see these issues (or similar to thereof) again.

I respectfully ask you to consider this vast trove of knowledge which is inaccessible.

**Comment by derekbruening** [comment]
All information in all bug reports filed after the code was open-sourced in Feb 2009 are in the github tracker.
