### ISSUE TITLE
Add handling of sigprocmask-bundling syscalls: epoll_pwait and pselect

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [DynamoRIO/dynamorio#2759]
Hi,

See attached program which shows different behaviour when started native or with drrun.

description:
- A signal handler for SIGUSR is used
- Signal SIGUSR1 is blocked
- epoll_pwait with an empty sigmask is used to poll for the signal

native:
- the handler for SIGUSR1 is called whenever the signal is send

with drrun:
- the handler is not called
- as soon as another signal is send (e.g.SIGUSR2, not blocked), the SIGUSR1 handler is called
- from then on the program works as exepected

With epoll_wait, it seems to work fine. Unfortunately, that is not an option in my case :(

Best regards,
Ralf

[epoll_wait_bug.cpp.txt](https://github.com/DynamoRIO/dynamorio/files/1551651/epoll_wait_bug.cpp.txt)

**Comment by derekbruening** [comment]
Today DR does not properly handle these syscalls that bundle sigprocmask with another operation: epoll_pwait and pselect.

If you'd like to submit a patch to add this support we would welcome the contribution.

**Comment by derekbruening** [comment]
Xref #2311 where there is a proposal to make the signal mask native for as many signals as possible which would simplify implementation here.

**Comment by egrimley** [comment]
The list of syscalls in `syscall_linux_uapi.h` was complete when I made it. Several traditional system calls are absent from arm64 and other recent Linux architectures because they are special cases of other system calls and therefore unnecessary. For example, there's also no `open` because it's a special case of `openat`. Probably `poll`, `select` and `epoll_wait` are special cases of `ppoll`, `pselect6` and `epoll_pwait`, respectively.

**Comment by hgreving2304** [comment]
@egrimley ,

> Probably poll, select and epoll_wait are special cases of ppoll, pselect6 and epoll_pwait, respectively.

Yes, poll == ppoll(.., NULL), select == pselect6(.., NULL), etc.

**Comment by hgreving2304** [comment]
This issue here (i2759) should be left open to address the fact the for the original poll, epoll_wait, select system calls, DR does not manage the native signal mask correctly. This means that one of the natively(!) executed system call above may be interrupted by signals that should be ignored or vice versa.

Xref #3240 that explains that in addition to this issue here, the atomicity of the p* versions is not emulated correctly. The race condition that the p* version of the system calls manages to prevent *can* happen in DR.

**Comment by hgreving2304** [comment]
Ignore ref to i#2759. Should be i#2868.

**Comment by derekbruening** [comment]
I believe this should be closed as the base handling is in place.  There are some not 100% handled aspects but those are separate issues: #3240, #2311
