### ISSUE TITLE
Test failures with gcc 6 and recent Linux distro

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2868]
On a recently upgraded Linux machine these tests are now failing:

```
	 21 - code_api|common.nativeexec_exe (Failed)
	 22 - code_api|common.nativeexec_bindnow (Failed)
	 24 - code_api|common.nativeexec_exe_opt (Failed)
	 25 - code_api|common.nativeexec_bindnow_opt (Failed)
	 67 - code_api|linux.sigcontext (Failed)
	155 - code_api|client.signal (Failed)
	184 - code_api|client.pcache-use (Failed)
	284 - code_api|api.static_sideline_FLAKY (Failed)
```

The failure are likely related to upgrading to gcc 6 and perhaps other pieces of the distro.

**Comment by Carrotman42** [comment]
I debugged the pcache-use failure to module_has_text_relocs:

https://github.com/DynamoRIO/dynamorio/blob/8fafbbc1849d719c4eea0e31318b401b4816fbff/core/unix/module_elf.c#L1060

On my machine, at some point during the test after it prints out the "Estimation of pi" message, the process encounters a segfault while trying to read the `dyn->d_tag` value during the first loop iteration. Note that `dyn` is some value which appears to be a valid pointer rather than NULL; in one run it was `0x00007f663f54fdb8` and is just in a part of memory which is not r/w accessible. From /proc/pid/smaps for that same run:

    7f663f54f000-7f663f74f000 ---p 00000000 00:00 0 
    Size:               2048 kB
    Rss:                   0 kB
    Pss:                   0 kB
    Shared_Clean:          0 kB
    Shared_Dirty:          0 kB
    Private_Clean:         0 kB
    Private_Dirty:         0 kB
    Referenced:            0 kB
    Anonymous:             0 kB
    AnonHugePages:         0 kB
    ShmemPmdMapped:        0 kB
    Shared_Hugetlb:        0 kB
    Private_Hugetlb:       0 kB
    Swap:                  0 kB
    SwapPss:               0 kB
    KernelPageSize:        4 kB
    MMUPageSize:           4 kB
    Locked:                0 kB
    VmFlags: mr mw me sd

**Comment by hgreving2304** [comment]
The failures of the common.nativeexec tests were due to -pie default in newer distros, see above.
