### ISSUE TITLE
[Question] Is it possible to build a statically linked ddrun in Linux (including libc)

### ISSUE THREAD

**Issue by sidkshatriya** [DynamoRIO/dynamorio#3305]
Is it possible to build a fully static drrun binary? In other words, I want to statically link in a libc.a and want ldd to to report no dependencies. I also want to statically link in a client.

Also, ideally I'd like to statically link in the musl c library.

The objective of doing all this is to add some (compile time) instrumentation on the above static binary. If I have all the sources compiled into this binary then I will be able to add static instrumentation to all the code otherwise I won't...

Does this make sense? Are there other ways to achieve this?

Restated, right now we have the dynamorio applications that are dynamically instrumented. But, I also want to instrument dynamorio and all its dependencies -- but that needs to happen at compile time.

**Comment by derekbruening** [comment]
Generally the users list should be used for questions, rather than filing an issue in the tracker.

It sounds like you don't want drrun, you want to link DR into an app.  That is supported: #975.  See the various tests in the code base like suite/tests/api/static_detach.c or clients/drcachesim/tests/burst_static.cpp.

Please switch any further questions to the users list.

**Comment by derekbruening** [comment]
Glancing at this again I may have misread it -- not sure I understand: instrument the tiny drrun launcher tool?  Have DR self-host?  Maybe ask again on the list.
