### ISSUE TITLE
Switch Travis to Xenial for more recent toolchain

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3456]
This issue covers updating our Travis platform from Trusty (14.04) to Xenial (16.04).  Trusty is using an old 4.8.4 gcc which makes it hard to reproduce toolchain-related failures locally.

Quoting @hgreving2304 

> 4.8.4 is very old and it looks like it doesn't even support Sandybridge (1st gen AVX). Though it seems to support -mavx. But for anything w/ AVX (e.g. tests), a newer version would be better.

**Comment by hgreving2304** [comment]
Looks like 4.8.4 doesn't even support "ymm" in the clobber list (looks like the C-frontend does not know AVX registers at all). We def. need this for tests.

**Comment by umarcor** [comment]
As a suggestion, it is straighforward to run docker containers in Travis, so you are not constrained by the tool version available on the default machine provided by them, be it Trusty or Xenial. Moreover, using docker images helps reproducibility, as the environment in the CI system is the same as the local setup of the user/developer.

For example, in https://travis-ci.com/umarcor/dbhi/builds/104035170 DynamoRIO is built for amd64, arm32v7 and arm64v8 (jobs 86.2, 86.5 and 86.4, respectively). Execution time for arm platforms is almost hiting the time limit (50min), because QEMU (user-mode) is used under-the-hood (see https://github.com/umarcor/qus).

**Comment by hgreving2304** [comment]
gcc-5 and gcc-6 that should be available in Xenial covers AVX and AVX-512
which was the motivation to switch toolchains, so we might not need that,
but we'll keep that in mind. Thanks for the tip
