### ISSUE TITLE
drwrap_get_retval problem

### ISSUE THREAD

**Issue by s0i37** [DynamoRIO/dynamorio#3511]
Hello. I have a trouble. I have a code with
`
to_wrap = (app_pc)dr_get_proc_address(handle, "CreateFileW");
drwrap_wrap(to_wrap, createfilew_pre, createfilew_post);
.....
static void createfilew_post(void *ctx, void **data)
{
int handle = (int) drwrap_get_retval(ctx);
}
`
And I can't obtain to right `handle` value.
And I get `handle` 0xffff8600 instead of 0xffffffff or 0x9300 instead of 0x30
What I make wrong?

**Comment by Carrotman42** [comment]
The issue tracker are for tracking specific bugs and features. For general user questions, please post to our user group: https://groups.google.com/forum/#!forum/dynamorio-users.

As a quick response before you post there: it is very hard to guess at exactly what the problem is in your situation without a small, self-contained reproducer in the form of code which actually compiles. While you provided some code, it's completely possible that the bug lies elsewhere in code you have not provided us. Without this full minimal reproducer it is hard to guess correctly at what could be wrong.
