### ISSUE TITLE
cmake -G"Visual Studio 10" .. fails

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3555]
cmake -G "Visual Studio 10" .. fails with error:
`\dynamorio\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

I've all prerequested tools and doing as in wiki:
https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build

**Comment by derekbruening** [comment]
I have never seen such an error.  Unless this is related to #3363 and it works with a version prior to the version implicated there (@dvfdr43, does it?), this is probably specific to VS2010?  We do not officially support VS2010.  Even if this issue is resolved, our code will fail to compile due to VS2010 not supporting C99 variable declarations in the middle of blocks.  Visual Studio 2013 Update 5 is needed as stated on the wiki (Update 4 will fail due to a compiler bug of not handling a variable declaration right after an `if` statement.)

**Comment by derekbruening** [comment]
Closing under the presumption of VS2010.  Please ask to re-open if this same thing happens with VS2013+.

**Comment by dvfdr43** [comment]
No, I'm using VS2013 with update 5
