### ISSUE TITLE
prof_pcs not working with multi-threaded program

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#359]
_From [qin.zhao@gmail.com](https://code.google.com/u/qin.zhao@gmail.com/) on November 28, 2010 14:59:46_

Hi, 

I found the SVN version of DynamoRIO not working with multi-threaded programs under the profiling mode (-prof_pcs). The program aborts with an assertion failure. It would be great if you can take a look. Thanks a lot.  

Configuration: 
Ubuntu 10.04
Linux kernel 2.6.32-25-generic
DynamoRIO: SVN revision 494 . Built with DEBUG and INTERNAL on. 

Program:
\#include \<stdio.h>
\#include \<pthread.h>

void *foo(void *arg) {
    fprintf(stderr, "&#37;d\n", (int)arg);
}

int main() {
    pthread_t t1, t2; 
    pthread_create(&t1, NULL, foo, (void *)1);
    pthread_create(&t2, NULL, foo, (void *)2);
    pthread_join(t1, NULL);
    pthread_join(t2, NULL);
    return 0;
}

Command line: 
DYNAMORIO_OPTIONS='-prof_pcs' ~/Research/dynamorio/install-debug/bin/drrun ./test-thread

Error message:
\<Application test-thread (18101).  Internal Error Internal DynamoRIO Error: /home/jingyue/Research/dynamorio/dynamorio-svn/core/linux/pcprofile.c:123 info->thread_shared
(Error occurred @252 frags)
version 2.1.0, custom build
-prof_pcs 
0x210f39f0 0x001cab70
0x210f3b60 0x002ecdb0
0x210f3b90 0x002e0a5b
0x210f3c10 0x002afffd
0x210f3c60 0x2104e953
0xbf91a9e8 0x003880eb
0xbf91aa48 0x0804856a
0xbf91aa78 0x00401bd6
0xbf91aaf8 0x08048461>

Best,
Jingyue

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=359_

**Comment by byron-hawkins** [comment]
The issue could be trivially fixed this way:

    if (shared_itimer) {
        ASSERT(parent_info != NULL);
        info = (thread_pc_info_t *) parent_info;
    +   dcontext->pcprofile_field = parent_info;
    +   info->thread_shared = true;
        return;
    }

But when the alarm fires, there are several rank order violations while looking up fragments and other such normal profiling activity (`fcache_unit_areas`, `report_buf_lock`, etc.) So for the profiler to work correctly, it needs to operate in a read-only manner WRT external structures (though it could write-lock its own private structures). It also needs to fail gracefully in the case that a racy read creates a garbage condition on the profiling thread, e.g. the fragment hashtable is being resized while the profiler is trying to lookup fragments. Basically, the profiler would have to operate completely lock-free. Is this possible? 

If the profiler cannot operate lock-free, then it can never be used with multi-threaded targets, since there is no possible lock rank that allows it to do work:

1. The lock rank must be innermost, because any operation may be interrupted by the alarm, and
1. The lock rank must be outermost, because it must acquire other locks for various profiling activities.

Going by experience, it does work for the `shared_itimer_lock` to be held orthogonally to all other locks. For example, I can run octane with "-prof_pcs" (on release DR) hundreds of times, and although it violates the lock rank *ad infinitum*, it still executes the benchmarks correctly every time. If the profiler has nothing of its own to lock, then it may be safe for the profiler to operate lock free. But this may not work for all multi-threaded targets--I only know about octane.

**Comment by derekbruening** [comment]
> But when the alarm fires, there are several rank order violations while looking up fragments and other
> such normal profiling activity (fcache_unit_areas, report_buf_lock, etc.) 

Please elaborate on this: what is the actual rank order sequence?  The thread that receives the alarm only acquires locks for its own whereami==WHERE_FCACHE.  For core DR, this means it does not hold any locks on its own, so how did it hit a rank order?  Some client actions never used by DR, such as clean calls that do not change whereami, could potentially be a problem that was not properly solved for this old pcprofile module -- is that what you are hitting?  Also note that we do *not* consider a rank order that shows up while holding report_buf_lock to be a rank order problem -- it is a problem of the core bug that is raising that error at a fragile point.  What is the error being reported?

**Comment by byron-hawkins** [comment]
Here's the sequence:

1. profiler alarm fires
2. `handle_alarm()` grabs the `shared_itimer_lock` having rank 0x5e (i.e., `shared_itimer_lock_rank`, which is next to innermost). See signal.c:5693 in TOT.
3. `pcprofile_alarm()` attempts to grab the `fcache_unit_areas->lock` having rank 0x48, via `fragment_pclookup()`. See pcprofile.c:258 in TOT.

So by calling `fragment_pclookup()` in step 3, the profiler violates the constraint of not acquiring locks. But the `fragment_t` is needed for printing the nice profiler report--otherwise it could only print a jumble of pcs that may be impossible to resolve after the fact (e.g. if the hotspot is in translated JIT code, where hundreds of different JIT fragments can be written to the same pc).

**Comment by derekbruening** [comment]
So the itimer sharng with the app did not consider the pcprof alarm properly.  A design tweak such as releasing the lock (after the timer intervals are adjusted) for the callback invocation should be considered -- someone should review the itimer lock design and what a callback is allowed to do (call itimer api routines?) and determine what's safe.

**Comment by byron-hawkins** [comment]
The profiler code that acquires other locks is fully contained in the alarm callback `pcprofile_alarm()`, which is invoked as the `cb` field like this:

    if (invoke_cb) {
        ...
        (*(*info->itimer)[which].cb)(dcontext, mc);  /* profiler's cb acquires other locks */
    }
    if (info->shared_itimer && acquired_lock)
        release_recursive_lock(info->shared_itimer_lock);

Since all the profiler structures accessed in `pcprofile_alarm()` are thread-local, it would be safe for that particular callback to release the `shared_itimer_lock` before invoking the callback. But since there are several other callbacks invoked at this point, including one exposed as a DR_API, I think it's not generally safe to always release the lock early. It seems like there are a couple of options:

1. Add a flag to `thread_itimer_info_t` that specifies whether to unlock before or after the callback.
2. Change the callback return value to `bool`, which indicates whether the lock is still held.

**Comment by derekbruening** [comment]
Callbacks from clients have no way to access shared_itimer_lock, so soln 2 doesn't quite make sense to me.  Maybe we should just special-case pcprof and not try to add an API-exposed way to request lock release in general.

**Comment by byron-hawkins** [comment]
The locking is slightly more complicated than I said above: all threads share a single instance of the profiler's `thread_pc_info_t` (which should perhaps be renamed to `process_pc_info_t`?) Currently the `thread_pc_info_t` is protected under the `shared_itimer_lock` for operations like `++`. This is impractical because the rank is next to innermost, so I suggest using a separate lock with a very low rank to protect the `thread_pc_info_t` while allowing other operations like fragment lookup.

The `PAPI` code (i.e., `perfctr.c`) is also using `shared_itimer_lock` to protect some global variables. One way to handle the special case for early unlock goes like this:

1. Add internal locks to `PAPI` and the profiler
2. Unlock the `shared_itimer_lock` early (pre-callback) for itimer `which` of `ITIMER_PROF`

Otherwise I'm not sure how to distinguish `PAPI` from the profiler within `signal.c`, since they are using the same instance of `thread_pc_info_t`.

Note that thread order can switch between early release of the `shared_itimer_lock` and subsequent acquisition of the (proposed) internal lock.

**Comment by derekbruening** [comment]
I thought the pcprof code had an argument that it did not need a lock.  The itimer lock is for ensuring the multiplexing is correct.  Always dropping the lock after itimer data struct updates but before the callback invocation seems like it might be fine as we should be ok w/ requested changes to itimers potentially still having an extra callback invoked if it's already in flight.  We just need to store the callback value in a local var as we can't access the shared data struct w/o the lock.

**Comment by byron-hawkins** [comment]
In a test of the early unlock on a smaller benchmark (Richards), I hit this assert when the profiler's `special_heap` is full, because it (intentionally) has no lock for allocation:

    /* Since vmm lock, dynamo_vm_areas lock, all_memory_areas lock (on
     * linux), etc. will be acquired, and presumably !su->use_lock means
     * user can't handle ANY lock being acquired, we assert here: xref PR
     * 596768.  In release build, we try to acqure the memory anyway.  I'm
     * worried about pcprofile: can only fit ~1K in one unit and so will
     * easily run out...should it allocate additional units up front?
     * => PR 596808.
     */
    ASSERT(su->top_unit == NULL/*init*/ || su->use_lock);

A full run of Octane will generate at least 100x more samples than just Richards, so profiling long runs will require expanding this heap on the fly. It could be a CL option, to allow faster profiling of smaller runs.

**Comment by byron-hawkins** [comment]
When I run the annotation concurrency test with `-prof_pcs`, I still get various rank order violations--even with early release of the `shared_itimer_lock`. For example, if the interrupted thread is in DR allocating memory, it will have the `global_alloc_lock`, which will conflict with the profiler's acquisition of the `fcache_unit_areas` lock (to lookup fragments by pc). An especially tricky case is when the interrupted thread is holding a lock that the profiler needs to acquire--the profiler will certainly deadlock  if any such lock is not recursive and the acquisition code is not checking whether the lock is already held.

It's looking more like the profiler needs to acquire data in a lock-free manner, if that's possible.

**Comment by derekbruening** [comment]
Please see the whereami==WHERE_FCACHE comments above as that is the problem that needs to be solved for clients.

**Comment by byron-hawkins** [comment]
See #140 for issues using -prof_pcs with a client.
