### ISSUE TITLE
Can not find asm_defines.asm include file with Visual Studio 2013 update 5 generator

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3613]
I've generate VS 2013 project as described in wiki, but when I'm trying to compile it getting error:

![image](https://user-images.githubusercontent.com/49196211/57772180-76a82a00-771d-11e9-972f-36e22fbbf4c1.png)

**Comment by dvfdr43** [comment]
Same to build from command line: 
`drlibc/drlibc_x86.asm(43): fatal error C1083: Cannot open include file: '../asm_defines.asm':`

**Comment by derekbruening** [comment]
Please provide the precise command line used and which shell and VS environment it was run in.

The only Windows build setup we can easily support is what's on our CI testing on Appveyor.  It is using Ninja.  You can see its logs here if that helps: https://ci.appveyor.com/project/DynamoRIO/dynamorio/builds/24547116

Building from the IDE is not something done by any of the small number of current regular contributors, though with CMake it's supposed to "just work".  If there is some error there and you'd like to fix it and support IDE building we would be happy to review pull requests.  More Windows-based maintainers are needed.

**Comment by dvfdr43** [comment]
Tool: `VS2013 x86 Native Tools Command Prompt` (same with `VS2013 x64 Cross Tools Command Prompt`)
command: `cmake -G"Visual Studio 12" ..`

**Comment by deroko** [comment]
This could solve your issue: https://github.com/deroko/dynamorio/tree/fix-3613

I've fixed small bug in nmake compile thus:
`cmake -G"Nmake Makefiles" ..` and then `nmake`should work for you out of the box.

**Comment by deroko** [comment]
Added also update for VisualStudio as is described on Wiki, but I haven't tested building on other systems, or if this has any other side effects. It only builds working copy of DynamoRIO on windows using VisualStudio 2013 update 5

**Comment by derekbruening** [comment]
Note again that our Appveyor CI uses `cmake -GNinja ..` which is guaranteed to work (and ninja is faster with nicer output than nmake or Windows build system I've seen).

The issue here seems to be with include directories, so I'm not sure that the PR #3650 which is about finding the assembler itself would be related?

**Comment by deroko** [comment]
No, finding assembler is not the issue here, only for nmake/jom. This one I've reflected in this commit: https://github.com/deroko/dynamorio/commit/cd07d9614676d361c8e2352dd832d644587d9417

However ninja building I haven't tried, but in worst case scenario there is some reference for people that still want to use nmake/vs2013 to build DynamoRIO.
