### ISSUE TITLE
Support drreg use outside of insertion phase combined with use in insertion phase

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3823]
drreg claims to support bare-bones use outside of the insertion phase, and it does, except it does not do the right thing if there are also drreg users in the insertion phase: it will not keep the reservations in the two phases distinct.  The same problem happens with multiple users in the same app2app or instru2instru phase.

If we do want to support use in other phases (the one being hit now is #2985 ), my proposal would be to add disjoint slot spaces or "arenas".  This may have to be done w/ global state to avoid breaking existing interfaces by adding an arena parameter:
```
drreg_set_arena(); 
drreg_reserve_xxx();
drreg_clear_arena();
```
and drreg_init w/ some DRREG_ flag creating a separate arena of the asked-for-number of slots.

We would need to work through interactions w/ regular insertion drreg and make sure it's going to work in other respects -- reg spilled in app2app will be spilled again (nested) but restored to 1st spill on app barrier.    Other client will not be able to get app's native value: ok to live w/?

**Comment by hgreving2304** [comment]
What about, instead of having global state and these setter/clear methods (still not clear whether this can rely on that we are globally synchronized or would need a lock/mutex), we tie the drreg_reserve_register() and drreg_reserve_aflags() etc. calls to phase? Starting with some default phase (NOPHASE) in case drreg is used outside of drmgr (is this even supported?). Any call to drreg_reserve_register() and similar API will tie the slot it is using to the current drmgr phase. In automatic management and optimizations in insertion phase, only slots of NOPHASE or insertion phase would be considered.

Yes this would not support several users in the same phase. But makes it simpler from an API point of view. If somebody would every need this, one could extend the scheme to passing custom phase types. It should just work then and no big changes would need to be made.

**Comment by derekbruening** [comment]
We had an offline discussion and this is the proposal I'm pushing:

Proposal: have drreg-inserted spills+restores added in the app2app phase marked
with a label or flag which drreg treats as an app instruction in its
insertion phase code.  This will then allow app2app use of registers to be
completely isolated from insertion phase: drreg will restore/respill around
them as necessary and re-use the register set in the most optimal way, just
like is done for app code.  (This also has a nice semantic feel to it:
app2app is supposed to be app code :))

drreg should expose a way to query the label, in case some clients want to
analyze reg liveness or sthg in ways that need to know about the app2app
spills.

This does *not* address multiple app2app events using drreg but I'm
suggesting we punt on that for now.

**Comment by hgreving2304** [comment]
xref https://github.com/DynamoRIO/dynamorio/pull/3899

**Comment by hgreving2304** [comment]
AFAICS (xref https://github.com/DynamoRIO/dynamorio/pull/3899) this issue here should now cover specifically mixed use of drreg from in and outside of the insertion phase and _multiple users_.

**Comment by abhinav92003** [comment]
> This will then allow app2app use of registers to be completely isolated from insertion phase: drreg will restore/respill around them as necessary and re-use the register set in the most optimal way, just like is done for app code. 

There can still be conflicts in spill slots. In https://github.com/DynamoRIO/dynamorio/pull/4863#issuecomment-824560991, I'm seeing that the spilled value of a register reserved in app2app phase (by `drx_expand_scatter_gather`) is clobbered by a different register's value spilled during later drcachesim instrumentation.

**Comment by derekbruening** [comment]
Was the mark-as-"app" proposal supposed to be combined with the disjoint slot spaces or "arenas" proposal?

**Comment by abhinav92003** [comment]
An alternative to the disjoint slot spaces design: When picking a spill slot, `drreg_reserve_register` can look at the instrs in the given `ilist` before `where` to find the spill slots that are already in-use (including those added by previous phases), and avoid re-using those spill slots. To make this easier, we can annotate spill/restore instrs with a `note` that describes the spill slot used.

I'm not complete sure yet how this will affect drreg analyses/optimisations though. E.g., in previous phases, if drreg skipped spilling a reg value on finding that it was already spilled previously to some spill slot, then we shouldn't use that spill slot in later phases even if we see a prior restore instr for it. 

Maybe we can add a new `drreg_bb_properties_t` that would just turn off optimisations and also enable the special slot-picking logic described above. We can use this for fragments where we have drreg uses in multiple phases.

**Comment by abhinav92003** [comment]
I'm working on adding drreg support for multi-phase aflags reservation. In the existing implementation, aflags are always spilled to slot 0. So the first part is to instead choose a slot every time we need to spill aflags (done in PR#4917). The next step is to enhance the reg state restoration logic to recognise the slot that aflags were spilled to. This is more complex due to the following:
1. aflags may be re-spilled if they are written-to by some app instr. We must be able to differentiate such re-spills from nested spills from other phases. Slots used by the former should be used to restore aflags. The way drreg deals with this problem in case of gprs is by using slot-id -- spills by the same phase always use the same slot id, so if we see a spill to a different slot id, we ignore it as a tool-spill. We can perhaps do the same for aflags, though it gets complicated on x86 because of (3) below.
2.  aflags spill is usually an `lahf` (on x86) or `mrs` (on aarchxx) followed by a spill slot write. While the latter is easy to identify in a stream of encoded instrs, the former is not that easy. If we see an `lahf` it may be an app instr as well. We can possibly work around this by looking at the next instr, which should be a spill slot write (similarly for restores). But it gets more complicated on x86 due to (3).
3. on x86, we may not have a spill slot write immediately after the `lahf` (or at all). This is an optimisation in drreg where the aflags are kept in xax until we can. I can see the same optimisation being applied to aarchxx too in future. I found that the existing logic to detect `aflags_in_xax` is broken too (#4933).

On AArchXX as it exists today, we can probably fix all these by ensuring that we use the same spill slot id for re-spills, and detecting aflags spill `mrs` by checking if the next instr is a spill slot write. But x86 would still be unresolved due to #4933. One possible design is to add support for #3801, and then pass metadata about aflags spill inlined in the ilist.

**Comment by abhinav92003** [comment]
Found another existing bug that affects `drreg_event_restore_state` for gprs. The following sequences causes failure to restore gpr value on fault: 
```
reserve reg r1, spill app-val to spill slot s1

tool-write to r1

spill tool-val of r1 to spill slot s2
restore app-val of r1 from s1 // drreg_event_restore_state loses its book-keeping of r1's spill slot here
app instr that reads r1
restore tool-val of r1

fault
```

`drreg_event_restore_state` loses its book-keeping when it sees the first restore of r1: https://github.com/DynamoRIO/dynamorio/blob/e8fc651f485f858127bf2394defc382d5cdff641/ext/drreg/drreg.c#L1897.

This is demonstrated by `test_asm_faultH` on PR #4932.
