### ISSUE TITLE
Using un-implemented droption types results in crashes/hangs instead of build or runtime up-front errors

### ISSUE THREAD

**Issue by edmcman** [DynamoRIO/dynamorio#3959]
**Describe the bug**
Using an option of type `uint64_t` causes DynamoRIO to exit with the following error:

`<Out of memory.  Program aborted.>`

**To Reproduce**
1. Pointer to a minimized application (ideally the source code for it and instructions on which toolchain it was built with).

**myclient.cpp**:
``` c++
#include "dr_api.h"
#include "droption.h"
droption_t< uint64_t > a(DROPTION_SCOPE_CLIENT, "arg", 0, "", "");
    void dr_client_main(client_id_t, int argc, const char *argv[]) {
     std::string b;
     int c;
     droption_parser_t::parse_argv(DROPTION_SCOPE_CLIENT, argc, argv, &b, &c);
   }
```
**CMakeLists.txt**:
``` cmake
set (CMAKE_CXX_STANDARD 11)
add_library(myclient SHARED myclient.cpp)
find_package(DynamoRIO)
if (NOT DynamoRIO_FOUND)
  message(FATAL_ERROR "DynamoRIO package required to build")
endif(NOT DynamoRIO_FOUND)
configure_DynamoRIO_client(myclient)
use_DynamoRIO_extension(myclient droption)
```
2. Precise command line for running the application.
`/path/to/dynamorio/build/bin64/drrun -c /media/data-linux/concolic-dynamorio-experiment/build/libmyclient.so -arg 1 -- ls`
3. Exact output or incorrect behavior.
After a few seconds, the program outputs:
`<Out of memory.  Program aborted.>`

Please also answer these questions:
 - What happens when you run without any client?
The app runs as expected.
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
```
<Starting application /bin/ls (15363)>
<Initial options = -no_dynamic_options -client_lib '/media/data-linux/concolic-dynamorio-experiment/build/libmyclient.so;0;"-arg" "0"' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<WARNING! symbol lookup error: libmyclient.so undefined symbol _ZN10droption_tIPvE19convert_from_stringENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE>
<WARNING! symbol lookup error: libmyclient.so undefined symbol _ZNK10droption_tIPvE17default_as_stringB5cxx11Ev>
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/media/data-linux/concolic-dynamorio-experiment/build/libmyclient.so' 0x00007f5c7660aa40
add-symbol-file '/tmp/DynamoRIO-x86_64-Linux-7.91.18219-0/lib64/debug/libdynamorio.so' 0x00007f5cba869c70
add-symbol-file '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' 0x00007f5cba300490
add-symbol-file '/lib/x86_64-linux-gnu/libm.so.6' 0x00007f5cb9ee0a80
add-symbol-file '/lib/x86_64-linux-gnu/libc.so.6' 0x00007f5cb9b042d0
add-symbol-file '/lib64/ld-linux-x86-64.so.2' 0x00007f5cb98b8f10
add-symbol-file '/lib/x86_64-linux-gnu/libgcc_s.so.1' 0x00007f5cb96a1ac0
>
<(1+x) Handling our fault in a TRY at 0x00007f5cbaa62092>
<Application /bin/ls (15363).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/signal.c:5261 pc != 0
(Error occurred @0 frags)
version 7.91.18219, custom build
-no_dynamic_options -client_lib '/media/data-linux/concolic-dynamorio-experiment/build/libmyclient.so;0;"-arg" "0"' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indca
0x00007f5bf66af5c0 0x00007f5cba904a66
0x00007f5bf66af810 0x00007f5cbab0517e
0x00007f5bf66af9b0 0x00007f5cbaac4b70
0x00007fff198c64b0 0x00007f5c7660ab57
0x00007fff198c6510 0x00007f5cbaa09b24
0x00007fff198c6550 0x00007f5cba87b5bb
0x00007fff198c6d80 0x00007f5cbab15762
0x00007fff198c7e30 0x00007f5cbaac4b5a
/media/data-linux/concolic-dynamorio-experiment/build/libmyclient.so=0x00007f5c76606000
/usr/lib/x86_64-linux-gnu/libstdc++.so.6=0x00007f5cba274000
/lib/x86_64-linux-gnu/libgcc_s.so.1=0x00007f5cb969f000
/lib/x86_64-linux-gnu/libm.so.6=0x00007f5cb9ed5000
/lib/x86_64-linux-gnu/libc.so.6=0x00007f5cb9ae3000
/lib64/ld-linux-x86-64.so.2=0x00007f5cb98b8000>
```

**Expected behavior**
DynamoRIO not to run out of memory.

**Versions**
 - What version of DynamoRIO are you using?
de511a72197e9b04a9732f33622fe7bc7fd12623
 - Does the latest build from
https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build solve the problem?
No.
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
- Is your application 32-bit or 64-bit?
64-bit

**Additional context**
An option that is 64-bits appears to trigger the problem.  Smaller option types do not.

**Comment by derekbruening** [comment]
These warnings when DR loads your client are the key:
```
<WARNING! symbol lookup error: libmyclient.so undefined symbol _ZN10droption_tIPvE19convert_from_stringENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE>
<WARNING! symbol lookup error: libmyclient.so undefined symbol _ZNK10droption_tIPvE17default_as_stringB5cxx11Ev>
```

Unmangled:
```
droption_t<unsigned long>::convert_from_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
droption_t<unsigned long>::default_as_string[abi:cxx11]() const
```

I.e., there is no implementation of a 64-bit int option type.  So the short answer is, this is not supported.  The droption docs should explicitly list which types are supported.

As to why the compiler doesn't refuse to build your code: I'm not sure.  We
have a base class droption_parser_t with a pure virtual function
default_as_string.  We have a templated child class which declares an
override of default_as_string, along with the other pure virtuals.  A
default implementation is provided for some of the overrides, but there is
no default implementation for default_as_string.  Now your code creates an
object of that templated class for a type for which there is no
implementation of default_as_string (with a vtable pointer of NULL, leading
to the crash).  Shouldn't the compiler complain, since for template code it
all has to be in the header right there and can't be separately compiled
and thus the compiler knows there is no implementation?

As to why it turns into OOM in release instead of reporting a crash: would take some
investigation (feel free if you are curious).  The crash is at PC 0 calling the non-existent
virtual function but you would think it would just report it.

Action items (@edmcman feel free to take a stab at these):
- Update droption.dox to explicitly list the supported types.
- Add default implementions for all overrides.  They will have to just fail, but parse_argv failing is better than a weird crash.
- May as well add 64-bit int specialization code (and test code).

**Comment by edmcman** [comment]
I've taken a first pass at this in #3965
