### ISSUE TITLE
Question about client and tool

### ISSUE THREAD

**Issue by qwerty62** [DynamoRIO/dynamorio#3967]
I've been testing and studying the example clients and tools with DynamoRIO. As far as I can tell, the clients and tools are similar in terms of event driven and callbacks registration. But I'm wondering what's the difference between clients and tools. What are clients and tools respectively suitable for? If I'm to develop new functions using DynamoRIO, on what occasion should I consider clients and when should I consider tools?
Any insight or explanation are much appreciated.
Thanks.

**Comment by AssadHashmi** [comment]
As a general rule clients are lightweight instruments for a particular task which you can quickly write based on an existing sample client or one you've written from scratch. Whereas tools are relatively more complex instruments for in-depth tasks which have been developed, tested and perfected by numerous people over many years.

Typically clients are one-off, short lifetime instruments which don't require extensive knowledge of the DynamoRIO API. Whereas tools are frequently used, long lifetime instruments which usually require deeper knowledge of use-cases and the API.

Note that general questions like this should be posted on the DynamoRIO user mailing list at https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/dynamorio-users rather than raising as an issue as the list has a wider audience and people with more insights and experience can answer your question.

**Comment by qwerty62** [comment]
Thanks a lot @AssadHashmi  I'll post the question on  the mailing list as you said.
