### ISSUE TITLE
CRASH in pre_inject_asm.asm on Windows x64 due to stack corruption

### ISSUE THREAD

**Issue by TomSie** [DynamoRIO/dynamorio#4283]
**Describe the bug**
I try to use the drpreinject.dll on Windows 10 (1909) X64. However, as soon as I register it via AppInit_DLLs, most applications crash. 

Imho this is due to the fact that the code generated by /core/arch/pre_inject_asm.asm on Windows X64 doesn't work properly.

The generated code is this:
![image](https://user-images.githubusercontent.com/16607413/81176828-03d73500-8fa6-11ea-8dcc-3d24a84b4d65.png)

In my test runs the jump at 0x53F25C78 is taken. This means, that the `push rcx` is not matched with a `pop`. As a result, the stack is currupted, and the process crashes.

Stack at function entry:
![image](https://user-images.githubusercontent.com/16607413/81177368-d343cb00-8fa6-11ea-9c7a-60b38f1505b4.png)

Stack at function leave:
![image](https://user-images.githubusercontent.com/16607413/81177427-ec4c7c00-8fa6-11ea-9cf8-3bcf85a3dfd5.png)

**Comment by johnfxgalea** [comment]
Thank you for the report. Can I ask for additional information please?

1) What commands are you actually running please
2) Is it possible to generate  logs and are there any suspicious messages?
https://github.com/DynamoRIO/dynamorio/wiki/Logfiles

**Comment by derekbruening** [comment]
Was AppInit support ever fixed for x64 for Windows 8+?
Doesn't look like it, since drrun will refuse to do -syswide_on for x64 (I assume you're setting AppInit manually here): https://github.com/DynamoRIO/dynamorio/blob/master/tools/drdeploy.c#L1593
So this is a dup of #1522.
As you can tell from how old Windows 8 is, there aren't key contributors who are using AppInit.  We are happy to review some pull requests if you would like to implement for x64 for recent Windows.  Let's move that to the original #1522 though.
