### ISSUE TITLE
CRASH (8.0.0) Travis MacOS build failing due to OOM

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#4347]
MacOS build on Travis is failing: https://travis-ci.com/github/DynamoRIO/dynamorio/jobs/356471150. There seems to be some OOM issue causing malloc to fail.

DR Version: 8.0.18439. Latest build using HEAD also fails.
OS: OSX; macOS 10.14.6; osx_image: xcode11.3; Xcode version: Xcode 11.3.1
64 bit build

The failure seems to appear between #4339 and #4342, so it's not caused by us.

**Comment by derekbruening** [comment]
We think this is related to Travis giving us a Mac VM with XCode 9.4.1 and OSX 10.13, instead of the 11.3 and 10.4 we are requesting and which we had back in February.

I checked a few builds and it looks like Travis made some change which caused the regression between our #4149 and #4150 on Mar 1-2:

+ #4140 11.3  Mar 1
+ #4149 11.3  Mar 1
+ #4150 9.4   Mar 2

Strangely the regression did not cause the immediate return of the failures we moved to 10.14 for.

**Comment by abhinav92003** [comment]
Travis macOS builds have started passing again, of their own accord. 

In #4354 I did an experiment where I reverted last 3 commits and re-committed them one at a time. These commits were failing on master when they were submitted.

Will close this issue. In a separate PR, I'll update xcode to our intended version as that is still useful.
