### ISSUE TITLE
Remove superfluous non-operands from LDXR, STXR, and related instructions on AArch64

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4532]
On AArch64 we have superfluous operands in the exclusive load and store instructions in DR's IR:

```
  0x0000ffff7d459b24  885f7c01   ldxr   (%x0)[4byte] $0x1f $0x1f -> %w1
  0x0000ffff7d459af0  885ffc01   ldaxr  (%x0)[4byte] $0x1f $0x1f -> %w1

  0x0000ffff7d459afc  88027c04   stxr   %w4 $0x1f -> (%x0)[4byte] %w2
  0x0000ffff7d459b28  8803fc02   stlxr  %w2 $0x1f -> (%x0)[4byte] %w3
```

These `0x1f` integers seem to be just part of the encoding and aren't actually operands.  I would expect them to not show up in the IR at all.

**Comment by derekbruening** [comment]
CLREX shouldn't have this 0 either:
```
 +52   m4 @0x0000fffd47084ff8  d503305f   clrex  $0x0000000000000000
```

**Comment by derekbruening** [comment]
There are still 2 references to `i#4532` in the code base: I think PR #5234 failed to remove/address those.

Also during the merge of PR #5234 the `Fixes` line was deleted from its final commit description: I guess it was the line in the PR itself that still managed to auto-close this?

**Comment by derekbruening** [comment]
CLREX still has an immediate int operand: `clrex  $0x0000000000000000`.  The code points at this issue:
```
core/ir/aarch64/instr_create_api.h:/* TODO i#4532: Remove this superfluous operand. */
core/ir/aarch64/instr_create_api.h-#define INSTR_CREATE_clrex(dc) instr_create_0dst_1src(dc, OP_clrex, OPND_CREATE_INT(0))
```
So I think this should be re-opened.

**Comment by joshua-warburton** [comment]
CLREX is a different case to the other instructions in that it does actually have an optional imm argument, but that argument is ignored, unlike the other superfluous arguments which were there to handle the potentially variable "sticky bits." It also defaults to a value of 15 for the imm if it is not set

This is similar to udf, which also has an ignored, optional operand.

Considering this, we should have two variants in order to comply with the spec:
11010101000000110011xxxx01011111  n   58        clrex                : imm4
11010101000000110011111101011111  n   58        clrex

**Comment by derekbruening** [comment]
OK, so an action item then is to remove the `TODO i#4532` comment then from the `INSTR_CREATE_clrex` macro?
