### ISSUE TITLE
New web documentation search seems not working

### ISSUE THREAD

**Issue by SweetVishnya** [DynamoRIO/dynamorio#4740]
Hi!

Could you, please, return the old flavored Doxygen search for DynamoRIO reference web site? The new one fails to find functions.

https://dynamorio.org/docs/index.html

https://dynamorio.org/search?query=dr_mutex_lock

**Comment by derekbruening** [comment]
It does find the page containing the function `dr_mutex_lock`, but it doesn't zero in on the anchor within the page since it currently searches at a page level.  The new search and the new doxygen integration into the top-level framework is a work-in-progress.

The old non-integrated html is still there at https://dynamorio.org/dynamorio_docs/ (just not linked to).

The doxygen search has several major shortcomings:
+ If you don't know what a symbol *starts with* you cannot find it: you cannot search for "lock" and find dr_mutex_lock which is pretty bad.
+ It does not search any of the prose, and we have extensive prose docs beyond just the function/data structure reference.
This will get worse as the wiki content is also integrated into the same site.

If you have experience in simple search solutions for jekyll-based sites and would like to help out that would be appreciated.

Having both searches there would just be confusing I think?  Tweaking the lunr-based search to be over menu entries would be an ideal solution: but while the entries are there in a JS array, the content for each is not: it would have to parse the page and stop at the next menu item's entry point.  Maybe the doxygen can be changed to make every sub-page section or subsection into its own page, which would then have the page list passed to lunr find things, as well as making the site nicer on mobile with smaller pages.

**Comment by derekbruening** [comment]
Xref #4111

**Comment by derekbruening** [comment]
> Having both searches there would just be confusing I think?

Maybe one input string could be passed to both and the results displayed side by side or sthg if the javascript for the two can be arranged that way.

**Comment by derekbruening** [comment]
Copying @johnfxgalea 's comment from https://github.com/DynamoRIO/dynamorio/issues/4111#issuecomment-780737033 over here as it directly relates to this search issue:

Another option might be to move the wiki & website to Docusaurus, which supports document search powered by Algolia DocSearch (or perhaps use this directly). However, I'm not sure if it works on HTML produced by doxygen, and might be an overkill anyways given our current setup.

https://v2.docusaurus.io/docs/search

**Comment by derekbruening** [comment]
@SweetVishnya I generated a set of keywords targeting anchors from the doxygen html patterns: it should be better now, with e.g. dr_mutex_lock's top hit a direct link.

**Comment by SweetVishnya** [comment]
That's better. What if we search for a prefix...

https://dynamorio.org/search?query=dr_mutex

I get no results.

**Comment by derekbruening** [comment]
This was my quick script for generating the data.  Better to search for something more stable than "memtitle", though it's all fragile if doxygen tweaks their output format.  I do a shift to drop "dr", but for other prefixes like "instr" we probably want to keep them.  Plus we should add the 2-token prefix "dr_mutex" as pointed out.  Maybe once this is translated into a permanent checked-in script as part of the automation it can then be improved.
Single example:
```
$ grep memtitle docs/*.html | grep dr_mutex_lock | perl -n -e 'if(m|docs/(\w+)\.html:.*href="(#\w+).*/span>(\w+)[\(\)]*</h2>|){@keys=split(/_/,$3);shift @keys;printf "window.data[\"%s-%s\"]={\"name\":\"%s-%s\",\"title\":\"%s in %s\",\"url\":\"/docs/%s%s\",\"content\":\"%s @keys\"};\n", $1,$3, $1,$3, $3,$1, $1,$2, $3;}'
window.data["dr__tools_8h-dr_mutex_lock"]={"name":"dr__tools_8h-dr_mutex_lock","title":"dr_mutex_lock in dr__tools_8h","url":"/docs/dr__tools_8h#a04beaefb3e0be6bd0dac39f76398ec1e","content":"dr_mutex_lock mutex lock"};
```

The whole thing:
```
$ grep memtitle docs/*.html | perl -n -e 'if(m|docs/(\w+)\.html:.*href="(#\w+).*/span>(\w+)[\(\)]*</h2>|){@keys=split(/_/,$3);shift @keys;printf "window.data[\"%s-%s\"]={\"name\":\"%s-%s\",\"title\":\"%s in %s\",\"url\":\"/docs/%s%s\",\"content\":\"%s @keys\"};\n", $1,$3, $1,$3, $3,$1, $1,$2, $3;}' >> keywords.js
```

I found no doxygen options for doing separate pages.

**Comment by derekbruening** [comment]
b4d3aee put in the scripting to add keywords for pefixes so "dr_mutex" now succeeds.  If anyone wants to improve it further the code is checked in, so have at it.  But it seems good enough for now so I propose closing this issue.
