### ISSUE TITLE
Missing unregistering of drmgr's tls slot in drcachesim's func_trace

### ISSUE THREAD

**Issue by sapostolakis** [DynamoRIO/dynamorio#4769]
The `func_trace` in drcachesim registers a thread-local storage (tls) slot during initialization (`func_trace_init()`) but does not unregister this slot during exit (`func_trace_exit()`).  This is problematic in a setting with multiples detaches and re-attaches and no resetting of the taken tls slots, since there is a slot that is not properly freed ("leaked" slot) potentially leading to a false shortage of available tls slots.

**Comment by derekbruening** [comment]
I would argue that the title is not really a bug.  The docs do not require unregistering anything at process exit; like global heap, the general cleanup tears everything down.  The bug is that drmgr_exit() does not reset all of its state for a re-attach (or possibly drmgr_init() does not clear it) with a statically-linked DR, which is a relatively new usage mode that causes problems for global state throughout DR and its libraries.  That state includes more than just whether slots are taken: the drmgr TLS value array is guaranteed to start out at NULL yet it is not reset either, so just having func_trace unregister does not solve the problem, nor solve it with say some 3rd-party client who does not unregister or who relies on the NULL value.

To reiterate, there will never be a problem here with regular DR usage, no matter how many re-attaches occur.  The only issue is with DR statically linked into the app.  The master issue for that is #2157.

I would suggest several action items:

1) Add a regression test that re-attaches with static-DR 100x or more.  The existing static tests only re-attach 3x or so.  Confirm it catches this problem.  The challenge is making it fast enough for the CI suite while still including as many components as possible to test their re-attached state.

2) Add a DR API routine to query whether a detach is in progress, to follow the core's convention of avoiding excess memset on non-detach exit.  The idea is to keep teardown for small processes as fast as possible so DR doesn't have horrible performance when running, say, a series of shell scripts and utilities they launch, all short-lived processes.

2) Audit all the ext libs and add memsets if detaching where necessary.  Unfortunately there's no simple global solution, unless we try to have our own data section and zero it in bulk or something, which would almost certainly still have exceptions and problems.  Xref #2157, #2661, #4319.  Just another messy complexity of static DR, along with lack of resource isolation.

Even if we decided to enforce unregistering of TLS slots and/or other things at exit (which I think requires a documented compatibility break), we would still have all of the other problems and the above would still be needed; in that case we could split into a separate issue perhaps.

**Comment by sapostolakis** [comment]
Sorry, I did not intend to depict it as a bug but rather to have an issue matching the related pull request (#4770). Thanks for giving context and explaining the problematic scenario. I see your point that there is a more generic issue here that needs to be addressed and your action items seem reasonable next steps.
