### ISSUE TITLE
api.rseq test fails on AArch64

### ISSUE THREAD

**Issue by AssadHashmi** [DynamoRIO/dynamorio#4923]
Migrating the AArch64 Jenkins CI to an Ampere Altera machine caused a regression in the `api.rseq` test with:

`<Application /var/lib/jenkins/workspace/DynamoRIO-AArch64-Precommit/build/build_debug-internal-64/suite/tests/bin/api.rseq (247628). Failed to synchronize with all threads when detaching.>`

But only the debug build. The release build passes.

**Comment by derekbruening** [comment]
This reproduces in every run.  It is a hang during detach.  It looks like the detach thread keeps trying to suspend the other thread and fails to get it at a safe spot due to translation errors, so I think this is a translation bug.  I see:
```
recreate_app : pc is in F4(0x0000aaaae93c4970)
ilist for recreation:
TAG  0x0000aaaae93c4970
 +0    m4 @0x0000fffda6be0eb8  f9000380   str    %x0 -> (%x28)[8byte]
 +4    m4 @0x0000fffda6be0f20  f9401f80   ldr    +0x38(%x28)[8byte] -> %x0
 +8    m4 @0x0000fffda6be0fe8  f902b801   str    %x1 -> +0x0570(%x0)[8byte]
 +12   m4 @0x0000fffda6be0c28  f9400380   ldr    (%x28)[8byte] -> %x0
 +16   L3 @0x0000fffda6be0ca8  d2800021   movz   $0x0001 lsl $0x00 -> %x1
 +20   L3 @0x0000fffda6be0d28  17fffffe   b      $0x0000aaaae93c4970
END 0x0000aaaae93c4970

unsupported mangle instr: str    %x1 -> +0x0570(%x0)[8byte]
recreate_app -- invalid state: unsup=1 in-mangle=1 xl8=0x0000aaaae93c4970 walk=0x0000aaaae93c4970
recreate_app -- not able to fully recreate context, pc is in added instruction from mangling
recreate_app: moving 0x0000aaaae93c4970 inside rseq region to handler 0x0000aaaae93c4988
recreate_app -- found ok pc 0x0000aaaae93c4988
        restoring stolen register to 0x0000ffffa73061a0
thread 3094900 not at safe spot (pc=0x0000aaaae93c4988) for 5
Synch failed!
Not all threads synched looping again
```

I think it moves the thread into its rseq failure handler, which causes the thread to re-try.
So we end up with an infinite loop.
There is a max count of tries to suspend but maybe the test timeout hits first.
