### ISSUE TITLE
Fix tool.drcacheoff.rseq test regression

### ISSUE THREAD

**Issue by AssadHashmi** [DynamoRIO/dynamorio#4924]
Migrating the AArch64 Jenkins CI to an Ampere Altera machine caused a regression in the `tool.drcacheoff.rseq` test:

`  *** postcmd failed (1): ERROR: Usage error: Unknown option: -test_mode`

**Comment by AssadHashmi** [comment]
The usage error above has been fixed by #4929 but the test now fails with `failed to match expected output`.

**Comment by derekbruening** [comment]
I believe GA CI Linux is hitting this same failure on Ubuntu 20.04 in release x86-64, and this is blocking our upgrade.

**Comment by derekbruening** [comment]
#4953 is the issue covering the upgrade

**Comment by derekbruening** [comment]
It looks like it's just not passing -test_mode in release and that's why it
doesn't print that it passed the invariants.
I think the only reason is I was using assert(), but no more after PR #5077.

Xref where I was going to add a -simulator_type=invariant_checker for #5076.
But here we want to run two simulators at once: so leave the -test_mode for
that and just enable for release build?  Slight extra overhead to check for
the flag in analyzer_multi but should be fine.
