### ISSUE TITLE
Bug with instr_compute_address()

### ISSUE THREAD

**Issue by theMarina** [DynamoRIO/dynamorio#5389]
I am trying to use `instr_compute_address()`, to compute the effective address of memory operands and it seems to often ignore the values of the registers in computing the address.

Here is an example of an instruction that triggers this bug:
```
0x00007fa3e89bb320 mov    %rax -> 0x58(%rsp)[8byte]
```

Here is an example of the wrong output:
```
dst_addr = 0x0000000000000058 
```

Here is a stripped version of my code that is invoked within a clean call:
```
static void clean_call(app_pc pc)
{
	void *drcontext = dr_get_current_drcontext();

	dr_mcontext_t mcontext;
	bool ret = dr_get_mcontext(drcontext, &mcontext);
	DR_ASSERT(ret);

	instr_t	instr;
	byte* res = decode(drcontext, (byte*)pc, &instr);
	DR_ASSERT(res != NULL);
	
	app_pc dst_addr = instr_compute_address(&instr, &mcontext);
	dr_fprintf(STDERR, "dst_addr = %p\n", dst_addr);
}
```

**Comment by derekbruening** [comment]
There are several bugs in your code.

- You did not fill in the size or flags fields of `mcontext`.  Almost certainly the `rsp` field is not bothered to be filled in because the uninitialized flags field doesn't ask for it.  Please see the docs https://dynamorio.org/dr__ir__utils_8h.html#a9e348b2596b8750ce3fad234ab022ced

- You did not initialize `instr` (https://dynamorio.org/dr__ir__decode_8h.html#a5ca2a278008e547130218e8cfde44e3d "Assumes that instr is already initialized")
