### ISSUE TITLE
it can't get plt symbol name by calling drsym_lookup_address

### ISSUE THREAD

**Issue by liang00fan** [DynamoRIO/dynamorio#5566]
**Describe the bug**
the symbol of .plt's addr is 0x0,there are some of symbol is rela. it's position is 

[12] .plt              PROGBITS         0000000000000650  00000650
       0000000000000070  0000000000000010  AX       0     0     16
  [13] .plt.got          PROGBITS         00000000000006c0  000006c0

while i get the app_pc of that, it can't get symbol name by calling drsym_lookup_address. i found such offs is 0x0 in the drsym_obj_addrsearch_symtab. how to fix it?

        size_t lo_offs = mod->syms[i].st_value - mod->load_base;
        size_t hi_offs = lo_offs + mod->syms[i].st_size;

**Versions**
 - What version of DynamoRIO are you using? 9.01
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem? not try
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.) ubuntu
- Is your application 32-bit or 64-bit? 64bit

**Comment by derekbruening** [comment]
You're expecting the names of ELF sections to be in the symbol table?  That is not usually the case.  Try running `readelf -s` on your binary and you will see the symbols that `drsyms` is going to find: it does not include the names of sections.

Please ask further questions like this on the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users instead of filing issues, as the list will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial.

**Comment by derekbruening** [comment]
> i know it could get the offset form readelf -s. but there are no address before running .i think dynamorio didn't consider this case.

?  I don't think you read my comment https://github.com/DynamoRIO/dynamorio/issues/5566#issuecomment-1187687137 properly.  Please re-read: the address of the .plt section is *not* in the symbol table and so it is *not* available from drsyms (nor from `readelf -s`).
