### ISSUE TITLE
Add CI support for RISCV64

### ISSUE THREAD

**Issue by shiptux** [DynamoRIO/dynamorio#5798]
Because of there is not a CI runs on RISCV64, so it is hard to find some issues in time. (Such as #5782 )

**Comment by derekbruening** [comment]
For a new project like RISC-V support there are many, many missing pieces and we would prefer to have one container issue (#3544) during the early stages covering all work; only once support is mature would we file separate bugs on each remaining missing piece.  I.e., please use the existing issue #3544 for RISC-V work rather than filing new issues.  Closing this to fold it into #3544.
