### ISSUE TITLE
AArch64 CCMP is not marked as reading NZCV, nor writing NZCV unconditionally

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#6871]
The `CCMP` instruction (and its variants) when decoded by DR is not marked as reading NZCV.  codec_v80.txt should list it as `rw` instead of just `w`.

Furthermore, because the instruction is predicated, calling `instr_get_eflags(instr, DR_QUERY_DEFAULT)` returns `0` without even the written NZCV.  The instruction's behavior does vary: what's written to NZCV varies.  But it always writes to NZCV, so arguably `DR_QUERY_DEFAULT` should return the write.  This may need some discussion though.  There is certainly existing code using `DR_QUERY_DEFAULT` and it causes problems with `CCMP`.

**Comment by AssadHashmi** [comment]
> The instruction's behavior does vary: what's written to NZCV varies. But it always writes to NZCV, so arguably `DR_QUERY_DEFAULT` should return the write.

I think so.
Does this mean that because NZCV is always written for conditional compares, `DR_QUERY_DEFAULT` should essentially behave like `DR_QUERY_INCLUDE_ALL` on AArch64 for these types of instructions?

> There is certainly existing code using `DR_QUERY_DEFAULT` and it causes problems with `CCMP`.

Are these `DR_QUERY_DEFAULT` problems with just`instr_get_eflags()` or other `instr_*()` calls related to conditional codes? I want to get an idea of the broader context/use-cases for the `DR_QUERY_ ` parameters to fix this as I'm not familiar with how this part of the API is used for analysis.

Did you find this bug with a test case?

**Comment by derekbruening** [comment]
> > The instruction's behavior does vary: what's written to NZCV varies. But it always writes to NZCV, so arguably `DR_QUERY_DEFAULT` should return the write.
> 
> I think so. Does this mean that because NZCV is always written for conditional compares, `DR_QUERY_DEFAULT` should essentially behave like `DR_QUERY_INCLUDE_ALL` on AArch64 for these types of instructions?

Our opinion is that the problem lies with `CCMP` being marked as having conditional behavior: we think it should *not* be marked predicated.  Its varying behavior is not that different from a logical or arithmetic operation combining source operands.  It should be a regular instruction and should not be marked as having conditional behavior.

> Did you find this bug with a test case?

An internal tool using the DR decoder hit this during testing.

**Comment by derekbruening** [comment]
The question is, if the predicate is removed from CCMP and CCMN, where would the flag variation be stored?  This goes back to prior discussions on opcode variation: how on other ISAs we have different opcodes for these types of variations.  I assume this would become an immediate operand holding the flags as a sub-opcode if we don't want to split the opcode.

We put in place a local workaround for this in the primary tool that was blocked on this, but there are other decoder uses so it would be good to get a real fix in place.

**Comment by AssadHashmi** [comment]
> The question is, if the predicate is removed from CCMP and CCMN, where would the flag variation be stored?

That's what I've been thinking about today.

> I assume this would become an immediate operand holding the flags as a sub-opcode if we don't want to split the opcode.

Yes, that would be my choice based on minimising changes to the current implementation.

**Comment by AssadHashmi** [comment]
Looking back to 2020, changes in https://github.com/DynamoRIO/dynamorio/pull/5216 were prompted by https://github.com/DynamoRIO/dynamorio/pull/4500. There was a long discussion in https://github.com/DynamoRIO/dynamorio/pull/4500 which revolved around the creation of new API functions for conditional types. The thrust was that we should avoid adding to the API without good reason. I think this is what @derekbruening  means by the comment above, "_This goes back to prior discussions on opcode variation_".

https://github.com/DynamoRIO/dynamorio/pull/4500 proposed 3 new API functions: `opnd_create_cond()`, `opnd_get_cond()` and `opnd_invert_cond()`.

Before deciding what to do here, we need to get back to basics and be clear about what we mean by '_predicated_' and '_conditional_' in this context, especially the distinction between them in order to be able to talk about these instructions and related API functions.

32 bit Arm has predicated instructions. This means that the instruction is executed only if a condition specified in the instruction encoding is true.

64 bit Arm does not have predicated instructions. This means that all instructions are executed.

32 and 64 bit Arm have conditional instructions which means that architectural state changes based on the `NZCV` condition encoded in the instruction.

**Comment by AssadHashmi** [comment]
I'm not implying we necessarily have to create a new set of conditional functions, but that we need to be clearer about the usage of `DR_PRED_`s in instruction operands/encodings, documentation and comments/language.

**Comment by derekbruening** [comment]
`dr_pred_t` was originally created for traditional predication as in AArch32 where instructions are not executed unless a condition is met.  We use it on other ISAs for their handful of instructions that behave in a similar manner: e.g., a conditional move.  So the `dr_pred_t` bits in the IR specify instruction behavior that varies in its most basic form that instrumentation cares about: whether source operands are read and whether destination operands are written.

`dr_opnd_query_flags_t` uses language like "all destinations are skipped for an instruction that is predicated and executes conditionally".  `instr_is_predicated` says "Returns whether \p instr is predicated: i.e., whether its operation is conditional."
`dr_pred_t` says "conditionally executed instructions".  The *operation* or *execution* being conditional is supposed to mean that it may not happen: it may not read all the inputs nor write all the outputs.

Looking back at https://github.com/DynamoRIO/dynamorio/pull/4500#discussion_r515920072 it listed 3 options:

> 1 - Create a new operand for cond.
> 2 - Split out the opcodes into specific cond types, e.g. ccmp_eq, ccmp_ne etc.
> 3 - Use existing dr_pred_type_t as in XINST_CREATE_jump_cond (alias for INSTR_CREATE_bcond).

We have also talked here about a variant of 1 where there is just an immediate operand that is not a new operand type: let's say that's option 4.

There is also option 5: let the `instr_t.eflags` field hold the condition.  There is no need for a separate operand or predicate bits: we can use the flags bits which are already there and which are meant for this purpose, showing what flags are read or written.  That sounds the simplest to me?  (Potential complications include assumptions that one can obtain the flags behavior purely from the opcode: but I think for AArch64 without split opcodes those types of assumptions of statically figuring things out from the opcode are already out the window: `instr_get_opcode_flags()` ends up calling `opcode_to_encoding_info` which is not implemented for AArch64, e.g.)

**Comment by AssadHashmi** [comment]
> There is also option 5: let the `instr_t.eflags` field hold the condition. There is no need for a separate operand or predicate bits: we can use the flags bits which are already there and which are meant for this purpose, showing what flags are read or written. That sounds the simplest to me?

Sounds good, I'm happy to go with using the `instr_t.eflags` field.

**Comment by derekbruening** [comment]
> > There is also option 5: let the `instr_t.eflags` field hold the condition
> 
> I'm not sure I follow what you are suggesting. Would we add a new 4-bit field to `instr_t.eflags` which contains the condition?

Hmm, I think I assumed there were would be a simple mapping from condition to which flags are read: but it is not so simple with some combinations like "Z==1 or N != V".

**Comment by jackgallagher-arm** [comment]
You can derive the read flags from the condition but it isn't a 1:1 mapping so you can't go the other way.
`EQ` -> `Z == 1` -> `EFLAGS_READ_Z`
`NE` -> `Z == 0` -> `EFLAGS_READ_Z`
so if `eflags == EFLAGS_READ_Z` you can't tell if the condition is `EQ` or `NE`.

We could change the `eflags` representation to store the condition code instead and derive the flags from it. That would make sense for the instructions we have been discussing in this issue but it wouldn't make sense for instructions like `cfinv` or `axflag` which manipulate flags without having an associated condition. It also seems like much too drastic a solution this problem.

Option 4 seems to me to be the path of least resistance.

**Comment by derekbruening** [comment]
> Option 4 seems to me to be the path of least resistance.

Agreed, given there is precedence for these immediates already.
