### ISSUE TITLE
tool.drcacheoff.invariant_checker failed with "Missing read/write records" 

### ISSUE THREAD

**Issue by ivankyluk** [DynamoRIO/dynamorio#7050]
When a instruction is preempted with no or incomplete read/write records, the invariant checker reports "Missing read/write records" error.

For example:

    ifetch       3 byte(s) @ 0x0000000010f94627 d1 60 20             shl    $0x00000001 0x20(%rax)[4byte] -> 0x20(%rax)[4byte]
    read         4 byte(s) @ 0x000015556606b238 by PC 0x0000000010f94627
    <marker: kernel xfer from 0x10f94627 to handler>

The shl instruction should be followed by a read and a write record. It was preempted in the above example and
the invariant checker reported an error.

The fix is to reset the expected read and write record counts when a kernel transfer event occurs.

**Comment by derekbruening** [comment]
It would help to know where in the block this `shl` is: it's the start of a block, right?  The prior instruction is a branch?  And there are more instructions afterward in this same block?  And the signal handler returns to this same `shl`?  Is the `shl` memref address the same after the handler?

Xref #5063.  There is drmemtrace discussion there: https://github.com/DynamoRIO/dynamorio/issues/5063#issuecomment-920147671.  However, as that issue says, a regular asynch signal would be delayed and would be delivered in between the two blocks.

If this were a real interruption of a block: it would hit #5790 or #5063.

There would not be any raw record for the store: that's elided.  That may explain why it's not there: it's not synthesized because the signal placement code fires and we short-circuit and skip further memrefs?  The raw2trace code calls handle_kernel_interrupt_and_markers() after each memref so if it matched after the first one it would have skipped the write.  But: it would also have matched on the call after the instruction: so why would any memref be appended before the signal marker?  Wouldn't the memref be after the signal markers in that case?
